cache:
  hosts:
    cachesrv00:
      ansible_host: 185.82.69.80
  vars:
    docker_install_compose: true
    docker_users:
      - ubuntu
    remote_cache_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          64633065656464663264346636323066653439396363366263313435323061663131393164323965
          6334643762313533666635323235343264653165303339370a363233326462653732366136633834
          30393564396334353531303236383932343534306430613937306330613537633032393537316638
          3166393730633461300a356661316261323535303565613062313562353061323630333539323465
          3230

