apiVersion: v1
kind: Pod
metadata:
  name: my-pod-fs
spec:
  containers:
   - name: pause
     image: ubuntu:latest
     command:
       - sleep
       - "3600"
     volumeMounts:
       - name: my-pvc
         mountPath: /tmp
  volumes:
   - name: my-pvc
     persistentVolumeClaim:
       claimName: my-pvc-fs
       readOnly: false