name: Nightly build (ubsan)
run-name: |
  ${{ github.event_name == 'workflow_dispatch'
      && format('Nightly build (ubsan) (manual)')
      || format('Nightly build (ubsan) (schedule)')
    }}
on:
  schedule:
    - cron: "0 2 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Build/test x86_64 using YA (ubsan)
    uses: ./.github/workflows/build_and_test_on_demand.yaml
    secrets: inherit
    with:
      build_target: 'cloud/blockstore/apps/,cloud/filestore/apps/,cloud/storage/'
      test_target: 'cloud/blockstore/,cloud/filestore/,cloud/storage/'
      build_preset: release-ubsan
      test_type: "unittest,clang_tidy,gtest,py3test,py2test,pytest,flake8,black,py2_flake8,gofmt"
      cache_update: true
      sleep_after_tests: 1
