name: Build VM image after nightly build
run-name: Build VM image after nightly build ${{ github.event.workflow_run.event}} ${{ github.event.workflow_run.id }}
on:
  workflow_run:
    workflows: ["Nightly build"]
    types:
      - completed
    branches: [main]
jobs:
  build_vm_image:
    name: Run packer to build VM image
    uses: ./.github/workflows/packer.yaml
    secrets: inherit
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.event == 'schedule'
    with:
      build: true
      file: 'ya_web_url_file'
      images_to_keep: ${{ github.repository == 'ydb-platform/nbs' && 7 || 3 }}
      remove_old_images: true
      update_image_id: true
      download_ya_archive: false
      image_prefix: 'gh-2204-auto'
      workflow_run_id: ${{ github.event.workflow_run.id }}
